version: '3.8'

services:
  web:
    build: ./app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/clientdb

      - DB_HOST=db
      - DB_NAME=clientdb
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: clientdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

volumes:
  pgdata: